### ISSUE TITLE
Deploy the application with a CI pipeline

### ISSUE THREAD

**Issue by cjkeilig** [jfranco1701/STEM-Capstone-2019#130]
- Public access to the site
- Testing purposes

**Comment by codykaup** [comment]
I think this is outside of the scope of the project. We might be able to add some automated testing to GitHub which is required to pass before merging into master though.

**Comment by cjkeilig** [comment]
There are plenty of demos of Azure DevOps and it has everything we need. It's free, can run tests, could build our docker image and it has a heroku cli for releases. I think it'd be a quick win.
