### ISSUE TITLE
Add input validation on frontend

### ISSUE THREAD

**Issue by codykaup** [jfranco1701/STEM-Capstone-2019#136]
Angular should have some functionality built in.

**Comment by maddagada** [comment]
**The input validation:** Verified each input element in the form, every element has clearly specified the minimum and maximum length of the input to be specified by the user with a mandatory field requirement.

**Form Validation:** By importing ReactiveFormsModule we can use inbuilt input and form validator directives (https://angular.io/api/forms/ReactiveFormsModule#directives)
