### ISSUE TITLE
Gather requirements

### ISSUE THREAD

**Issue by cjkeilig** [jfranco1701/STEM-Capstone-2019#46]
1. How do students sign up? Open signup, or 'email you a code' approach.
2. Define data model (fields)
3. Permissions, how does user get promoted to a certain 'role'.

**Comment by codykaup** [comment]
4. What’s the difference between the roles (counselor vs. teacher vs. parent)

**Comment by codykaup** [comment]
How should events be added/approved?

**Comment by jfranco1701** [comment]
7.  Should we concentrate on looks or functionality
